version: "3.3"

services:
  fastapi:
    build: services/fastapi/.
    deploy:
      replicas: 2
    ports:
      - "3000-3001:80"
  express_api:
    build: services/express_api/.
    environment:
      - PORT=3000
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - DB_PASSWORD=
    deploy:
      replicas: 5
    ports:
      - "2000-2004:${express_api_PORT}"
  database:
    restart: always
    build: services/database/.
    container_name: socks_inventory_db
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - "./services/database/pgdata:/var/lib/postgresql/data"