version: "3.3"

services:
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.joaomanoel.com.br`)"
      - "traefik.http.routers.whoami.entrypoints=web"